### ISSUE TITLE
Upgrade to Python 3?

### ISSUE THREAD

**Issue by imnotjames** [rmmh/skybot#175]
I wanted to open an issue to discuss what concerns there are - if any - on upgrading to Python 3 from 2.7.  At the very least, I'd be interested in trying to get python 3 compatible code up with `future` but there are no Python2-only dependencies, so I'm using Python 3 live.

I've already done a quick pass for the fork of skybot that I keep up, but it's always nice to push things back upstream. ( https://github.com/imnotjames/skybot/commit/960e8b6e1256f1d9d9f7011cd71433217815a966 )

I hit a few problems:

* There are no tests.  This makes it very difficult to know if something's broken or not.  Since most of the bot relies on outside APIs, and there's no culture to enforce tests, I'm not sure the best way to handle that.
* Without tests, I can't set up `tox` to check both 2 and 3 compatibility.  I'm manually running two bots right now with both 2 and 3.
* Instead of standard strings, we end up with binary strings in many cases.  These have to be correctly encoded / decoded to be valid.  I think I got them, but see the point about tests for cases where there might be problems..

Would there be interest in merging these changes upstream?

**Comment by rmmh** [comment]
I'm open to this. It's time to do the migration.

A few plugins have tests, but not many. I prefer tests in the same file as plugins for simplicity, which works fine with nosetests, and could probably be made to work with tox as well. Some simple http mocking would probably work to expand testing.

Skybot mostly treats everything as utf-8, and we should be able to move to standard strings in Python 3. The unicode conversions should mostly happen at the core/irc.py layer with the network protocol, and be transparent otherwise.

**Comment by imnotjames** [comment]
I've opened a pull request with migration between 2 and 3 - https://github.com/rmmh/skybot/pull/190

It allows skybot to run both 2 and 3 and has tox set up to test 2.7 and 3.7

**Comment by rmmh** [comment]
Thanks!
